apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Values.graphql.name }}-ingress"
  annotations: {}
spec:
  rules:
  - host: {{ .Values.graphql.ingress.prefix }}.{{ .Release.Namespace }}.{{ .Values.global.ingress.wildcard }}
    http: &http_service
      paths:
      - path: /
        backend:
          serviceName: "{{ .Values.graphql.name }}"
          servicePort: {{ .Values.graphql.service.default.port }}
  tls:
  - hosts:
    secretName: xip

# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   annotations: {}
#   name: "trialgraph-ingress"
#   annotations: 
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/ssl-redirect: "false"
#     nginx.ingress.kubernetes.io/proxy-connect-timeout: "14400"
#     nginx.ingress.kubernetes.io/proxy-send-timeout: "14400"
#     nginx.ingress.kubernetes.io/proxy-read-timeout: "14400"
#     nginx.ingress.kubernetes.io/proxy-body-size: 100m
# spec:
#   rules:
#   - host: trialgraph-ingress.argos.coreborne.linnovate.net
#     http: &http_service
#       paths:
#       - path: /
#         backend:
#           serviceName: "trialgraph"
#           servicePort: 8888
