apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.graphql.name }}"
  labels:
    app: "{{ .Values.graphql.name }}"
spec:
  type: ClusterIP
  ports:
  - name: "{{ .Values.graphql.service.default.name }}"
    port: {{ .Values.graphql.service.default.port }}
    targetPort: {{ .Values.graphql.service.default.targetPort }}
  selector:
    app: "{{ .Values.graphql.name }}"
