apiVersion: v1
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: "{{ .Values.graphql.name }}"
    version: "{{ .Values.graphql.version }}"
  name: "{{ .Values.graphql.name }}-configmap"
data:
{{- range $key, $val := .Values.graphql.configmap.data }}
  {{ $key }}: {{ $val | quote }}
{{- end}}
